# Generated by Django 4.2.10 on 2025-11-06 21:20

import apps.orders.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('total_price', models.PositiveIntegerField(verbose_name='قیمت کل (تومان)')),
                ('status', models.CharField(choices=[('pending', 'ثبت شده'), ('waiting', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('rejected', 'رد شده'), ('delivered', 'تحویل شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد معرف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.FileField(upload_to=apps.orders.models.get_receipt_upload_path, verbose_name='رسید پرداخت')),
                ('card_number', models.CharField(max_length=20, verbose_name='شماره کارت مقصد')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='سفارش')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL, verbose_name='تأیید کننده')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
    ]
