# Generated by Django 4.2.10 on 2025-10-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('telegram_id', models.CharField(blank=True, max_length=100, verbose_name='آیدی تلگرام')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='شماره موبایل')),
                ('message', models.TextField(verbose_name='پیام کاربر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='مشاهده شده توسط ادمین')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
    ]
