# Generated by Django 4.2.10 on 2025-10-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('guarantee_type', models.CharField(choices=[('metaK', 'متیک'), ('legend', 'لجند'), ('supertash', 'سوپرتاش')], max_length=20, verbose_name='نوع تضمین')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='تعداد موجودی (پارت)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر محصول')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
    ]
