# Generated by Django 4.2.10 on 2025-10-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='webp_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/webp/', verbose_name='تصویر WebP محصول'),
        ),
    ]
