# Generated by Django 4.2.10 on 2025-10-31 17:13

from django.db import migrations, models
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    for product in Product.objects.all():
        product.slug = slugify(product.name, allow_unicode=True)
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_webp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True, default='placeholder'),
            preserve_default=False,
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True),
        ),
    ]