# Generated by Django 4.2.10 on 2025-11-04 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ دسته')),
                ('icon', models.CharField(blank=True, help_text='کلاس آیکون (مثال: fa-solid fa-gamepad)', max_length=50, null=True, verbose_name='آیکون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_pinned', models.BooleanField(default=False, help_text='آیا این دسته باید همیشه در بالای لیست نمایش داده شود؟', verbose_name='پین شده')),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش دسته در منوها', verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category', verbose_name='دسته بندی'),
        ),
    ]
