# Generated by Django 4.2.10 on 2025-11-05 20:12

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_category_icon_remove_category_is_pinned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=timezone.now, verbose_name='تاریخ بروزرسانی'),
            preserve_default=False,
        ),
    ]
