# Generated by Django 4.2.10 on 2025-11-06 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ دسته')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر دسته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش دسته در منوها', verbose_name='ترتیب نمایش')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات متا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('guarantee_type', models.CharField(choices=[('metaK', 'متیک'), ('legend', 'لجند'), ('supertash', 'سوپرتاش')], max_length=20, verbose_name='نوع تضمین')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='تعداد موجودی (پارت)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر محصول')),
                ('webp_image', models.ImageField(blank=True, null=True, upload_to='products/webp/', verbose_name='تصویر WebP محصول')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
    ]
