# Generated by Django 4.2.10 on 2025-10-29 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پیام تلگرام')),
                ('message_text', models.TextField(verbose_name='متن پیام')),
                ('is_sent', models.BooleanField(default=False, verbose_name='ارسال شده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_messages', to='orders.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام تلگرام',
                'verbose_name_plural': 'پیام\u200cهای تلگرام',
                'ordering': ['-created_at'],
            },
        ),
    ]
